<?php
// Generated by the YunoHost installer. Holds static paths + broadcast config.
// Runtime-editable settings (Telegram credentials) live in
// __DATA_DIR__/settings.json and are managed via the web UI.

return [
    // Mounted subpath (e.g. "/btcpublisher"). Used by url_for() so all nav
    // links and form actions stay inside the app's permission scope —
    // otherwise SSOwat redirects every click to the YunoHost portal.
    'subpath' => '__PATH__',

    'db_path'        => '__DATA_DIR__/state.db',
    'settings_path'  => '__DATA_DIR__/settings.json',
    'lock_dir'       => '__DATA_DIR__',

    'node' => [
        'peer_host' => '__NODE_ONION__',
        'peer_port' => __NODE_PORT__,
    ],
    'tor' => [
        'socks_host' => '127.0.0.1',
        'socks_port' => __TOR_PORT__,
    ],

    'public_fallback'   => __PUBLIC_FALLBACK__,
    'primary_attempts'  => 4,
    'primary_backoff_s' => 30,
    'connect_timeout_s' => 90,
    'read_timeout_s'    => 30,
    'public_timeout_s'  => 30,
];
